# Generated by Django 5.1.6 on 2025-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('president', 'Society President')], default='student', max_length=20),
        ),
    ]
